### ISSUE TITLE
Sprint 1: Critter Finder

### ISSUE THREAD

**Issue by smacgregor** [TeamCritterFinder/CritterFinder#41]
Our first sprint is complete, please review. /cc @codepathreview @codepath

@scottrichards @cbaja 

Another fun project! We enjoyed getting to explore the PetFinder API and learning to work together.

<h2>Interesting Notes</h2>

We made really good progress getting the general flows and UI screens in place. We didn't focus much on making the UI pretty.

The material design library was invaluable when it came to building out search filters. We made heavy use of that library. Very slick.

<h2>Open Questions</h2>

We're looking forward to thinking about animations and how we'll implement the "Tinder" wipe mechanic for cycling through a list of pets.

Getting location from the GPS working with genymotion is an adventure. Thank you Nate for sharing the cliff notes for converting a latitude and longitude into an address. That came in handy for us and we learned how to set up an Async Task in order to do it!

**Comment by codepathreview** [comment]
## Group Sprint 1 Review

:+1:  Nice work creating wire-frames and creating stories for sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:
- Well created detailed stories/tasks on the project wiki.
- Nice way of splitting a parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.
- Work load needs to be divided equally among all members of the team. This is critical in working as a team and also gives equal learning opportunity to everyone involved. Please make sure everyone [contributes](https://github.com/TeamCritterFinder/CritterFinder/graphs/contributors) to the project in the next sprint.
- Group projects can reinforce skills that are relevant to both group and individual work including the ability to plan and manage time. For this reason, it is imperative that you group all detailed issues into [milestones](https://github.com/TeamCritterFinder/CritterFinder/milestones) representing sprints so that its easier for you to track progress of the project.
- Nice work creating and distributing tasks to create database schema and models. Good job on integrating with Parse.
- Consider creating a project wiki so you can have a thorough documentation of all design decisions made during the project.
- Good to see that your team created regular commits to sync up your code to avoid having multiple conflicts at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.
- Consider creating group [milestones/pull requests](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) to better track your progress and review each others code.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on. It is those little extra things you do that make everything feel more polished and desirable to use.

**Comment by smacgregor** [comment]
Thanks for the feedback @codepathreview @codepath.

Just an aside - https://github.com/TeamCritterFinder/CritterFinder/graphs/contributors should not be used to track project contributions. That github graph only tracks commits directly to master which is discouraged. It ignores all merges made through pull requests.

We use pull requests for our commits and none of those [changes](https://github.com/TeamCritterFinder/CritterFinder/pulls?q=is%3Apr+is%3Aclosed) will appear in that graph.

We also have been grouping issues into Sprint milestones which you can see here https://github.com/TeamCritterFinder/CritterFinder/milestones. Please let us know if you have suggestions on how we could be using milestones more effectively.

We're looking forward to wrapping up the functionality in the next sprint so we can start polishing the app!

Thanks again.

-Team Critter Finder
