### ISSUE TITLE
Browse : Consider making action bar off white

### ISSUE THREAD

**Issue by scottrichards** [TeamCritterFinder/CritterFinder#97]
Would this be app wide?

**Comment by smacgregor** [comment]
@scottrichards @cbaja 

Here's an example of what a white action bar would look like for us. If we make it white - I think we would have to make the X and heart buttons on the browse view more colorful - like Tinder instead of using the gray.

I'll show you on device tomorrow as it shows a little better on device.

I do agree with Brian that it makes the image of the pet pop more. But I think it makes the overall swipe screen look a little washed out - maybe coloring the button icons would help offset that.

<img width="526" alt="screen shot 2016-03-20 at 9 53 23 pm" src="https://cloud.githubusercontent.com/assets/1521460/13910887/9f176c84-eee6-11e5-8ce6-9cc7c1140909.png">
<img width="531" alt="screen shot 2016-03-20 at 9 53 56 pm" src="https://cloud.githubusercontent.com/assets/1521460/13910888/9f17e89e-eee6-11e5-907b-f934a3db8eb7.png">

**Comment by smacgregor** [comment]
And a screen shot keeping the blue font color but with a white action bar background color:

<img width="525" alt="screen shot 2016-03-20 at 10 02 17 pm" src="https://cloud.githubusercontent.com/assets/1521460/13910952/7271856a-eee7-11e5-9497-445f303e6df7.png">
